package network.hera.gamekit.network.transfer;

public enum TransferRejectReason {
    PLAYER_NOT_ONLINE,
    ADMISSION_NOT_FOUND,
    ADMISSION_EXPIRED,
    ADMISSION_PLAYER_MISMATCH,
    ADMISSION_TARGET_MISMATCH,
    TARGET_SERVER_UNAVAILABLE,
    CONNECTION_IN_PROGRESS,
    TRANSFER_CANCELLED,
    TRANSFER_SIGNAL_NOT_DELIVERED,
    SHUTTING_DOWN,
    REDIS_UNAVAILABLE,
    TRANSFER_FAILED
}
